# Generated by Django 2.0 on 2017-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default=None, max_length=200)),
                ('customer_type', models.CharField(default=None, max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('actual', models.FloatField()),
                ('expected', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
